language: go

go:
- 1.9.x

install:
- ./tool/init.sh

after_success:
- go get github.com/mattn/goveralls
- $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN

script:
- go build github.com/willeponken/picoshop/cmd/picoshopd
- ./tool/test_full.bash

env:
  secure: WFL7d8l3IbzRMNjbjxaGwSnai21QC3ks+LANIOR+SPay9lkj64NUmQwMGlLF/1eDLDR8at2ncBi/2OXZUcRkLV1I37h35Ldb3cdg37dEpTnLOF7mQC3qE2GVnsIGkioPCK6/0Du3Uew7yUT8gl0xY7GrwpfynBO1EqeAszYHlORewpaYa1cezqLYdXHihwvUWIfU3KeqjU7SlcOV1FQBvb6PrRne39UJCerqqChPK90abkhPEJBZ3lbr7KSCNHd8IB003jBYnvLL/FXmmqeRsFnTMBEmq0MLhrSx1OZuvCFd2kFDg88p5BsBBjnrqNMZjBbVcfbLwHCAFRn6kqArJfFIGYU1dc6bDQJvFiA9jRcoyOwXH8/A86ZKGtumsk8rR3arpv5QLwN+uv0puQvpFEg87a5E6JAUnW+P4QCRgG2ygegF0N484i0XtPqg1CMGOPwCIlmpkL9uRXbZSfQd51r+Ecee5wC2wF069q1Z/Em/pBNV9Vd2vkgKbJ66rdKjoCFwpidqWQGdDywDSwvnkWK0+B84Acw3cX0JguiV0PMrh86SuWMG7KWavVWIYni9n2zockQxXCp02RajML9GqK5Tztj7g01ZhYDr7D/rObmKWHKelA69UihIo9fbj8tG6btT6mntoIOiI64eC4oN2srBtlvhK2oTXODRC7SsFoY=
